apiVersion: apps/v1
kind:  Deployment
metadata:
  name: backend
  namespace: expense
  labels: # these are replicaset labels
    app: backend
    tier: app
    project: expense
spec:
  replicas: 2
  selector:
    # these are used to select the pod to create replicas
    matchLabels:
      app: backend
      tier: app
      project: expense
  template:
    metadata:
      # these labels belongs to pod
      labels:
        app: backend
        tier: app
        project: expense
    spec:
      containers:
      - name: backend
        image: bharath1106/frontend:v1
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: expense
spec:
  selector:
    app: frontend
    tier: web
    project: expense
  ports:
  - name: web-port
    protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port